## Append samples you want in your CSV to this file as resources ##
# Dev note: renaming these files is not allowed as operator-sdk later uses them
# to generate proper CSV documents
resources:
  - atlas_v1_atlasdeployment.yaml
  - atlas_v1_atlasproject.yaml
  - atlas_v1_atlasdatabaseuser.yaml
  - atlas_v1_atlasbackuppolicy.yaml
  - atlas_v1_atlasbackupschedule.yaml
  - atlas_v1_atlasteam.yaml
  - dbaas_v1beta1_atlasconnection.yaml
  - dbaas_v1beta1_atlasinventory.yaml
  - dbaas_v1beta1_atlasinstance.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
