apiVersion: atlas.generated.mongodb.com/v1
kind: FlexCluster
metadata:
  name: flexy
spec:
  connectionSecretRef:
    name: mongodb-atlas-operator-api-key
  v20250312:
    groupId: "60f1b3c4e4b0e8b8c8b8c8b"
    entry:
      name: flexy
      terminationProtectionEnabled: true
      providerSettings:
        backingProviderName: GCP
        regionName: CENTRAL_US

