name: CloudTests

on:
  workflow_call:

concurrency:
    group: cloud-tests-${{ github.ref == 'refs/heads/main' && 'main' || github.actor || github.triggering_actor }}
    cancel-in-progress: true

jobs:
  allowed:
    name: Allowed
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'merge_group' ||
      github.ref == 'refs/heads/main' ||
      (github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]') ||
      contains(github.event.pull_request.labels.*.name, 'safe-to-test')
    steps:
      - name: allowed message
        run: echo "Allowed to run"

  int-tests:
    needs: allowed
    uses: ./.github/workflows/test-int.yml
    secrets: inherit

  e2e-tests:
    needs: allowed
    uses: ./.github/workflows/test-e2e.yml
    secrets: inherit

  test-e2e-gov:
    needs:
      - allowed
    uses: ./.github/workflows/test-e2e-gov.yml
    secrets: inherit

  openshift-upgrade-test:
    needs: allowed
    uses: ./.github/workflows/openshift-upgrade-test.yaml
    secrets: inherit
