name: Compute test labels tool CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tools/compute-test-labels/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'tools/compute-test-labels/**'

jobs:

  compute-test-labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: CI checks
      working-directory: ./tools/compute-test-labels
      run: go build ./... && go test ./...