name: Make JWT tool CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tools/makejwt/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'tools/makejwt/**'

jobs:

  makejwt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'

    - name: CI checks
      working-directory: ./tools/makejwt
      run: go build ./... && go test ./...
