name: Promote Image

on:
  workflow_call:

jobs:
  # Promote image: this will be responsible for taking a tested image from an unofficial registry like
  # ghcr.io and promote it by adding it to an official registry (docker.io and quay.io)
  promote-image:
    runs-on: ubuntu-latest
    environment: release
    env:
      GHCR_REPO: ghcr.io/mongodb/mongodb-atlas-kubernetes-operator-prerelease
      DOCKER_REPO: docker.io/mongodb/mongodb-atlas-kubernetes-operator-prerelease
      QUAY_REPO: quay.io/mongodb/mongodb-atlas-kubernetes-operator-prerelease
    steps:
      - name: Checkout PR commit
        uses: actions/checkout@v6

      # Login in all the needed registries
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to Quay registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      # Prepare tags
      - name: Prepare image tag
        id: set_tag
        uses: ./.github/actions/set-tag

      - name: Prepare tag for promoted image
        id: promoted_tag
        run: |
          RAW_TAG="${{ steps.set_tag.outputs.tag }}"
          COMMIT_SHA="${RAW_TAG##*-}"
          echo "tag=promoted-${COMMIT_SHA}" >> $GITHUB_OUTPUT

      # Promote image to official prerelease registries
      - name: Move image to Docker Hub
        run: ./scripts/move-image.sh
        env:
          IMAGE_SRC_REPO: ${{ env.GHCR_REPO }}
          IMAGE_DEST_REPO: ${{ env.DOCKER_REPO }}
          IMAGE_SRC_TAG: ${{ steps.set_tag.outputs.tag }}
          IMAGE_DEST_TAG: ${{ steps.promoted_tag.outputs.tag }}
          ALIAS_ENABLED: ${{ github.ref_name == 'main' }}
          ALIAS_TAG: promoted-latest

      - name: Move image to Quay
        run: ./scripts/move-image.sh
        env:
          IMAGE_SRC_REPO: ${{ env.GHCR_REPO }}
          IMAGE_DEST_REPO: ${{ env.QUAY_REPO }}
          IMAGE_SRC_TAG: ${{ steps.set_tag.outputs.tag }}
          IMAGE_DEST_TAG: ${{ steps.promoted_tag.outputs.tag }}
          ALIAS_ENABLED: ${{ github.ref_name == 'main' }}
          ALIAS_TAG: promoted-latest
