name: Test Forked

on:
  pull_request_target:
    types: [labeled]
    paths-ignore:
      - 'docs/**'

concurrency:
  group: test-forked-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    with:
      forked: false
  
  unit-tests:
    uses: ./.github/workflows/test-unit.yml
    with:
      forked: false

  allowed-forked:
    name: Allowed action
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }} || contains(github.event.pull_request.labels.*.name, 'safe-to-test')
    steps:
      - name: allowed message
        run: echo "Allowed to run"

  int-tests:
    needs: allowed-forked
    uses: ./.github/workflows/integration-test.yml
    secrets: inherit
    with:
      forked: true

  e2e-tests-forked:
    needs: allowed-forked
    uses: ./.github/workflows/test-e2e.yml
    secrets: inherit
    with:
      forked: true

  openshift-upgrade-test:
    needs: allowed-forked
    uses: ./.github/workflows/openshift-upgrade-test.yaml
    secrets: inherit
    with:
      forked: true
